# Generated by Django 4.1 on 2022-09-18 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        ('user_account', '0001_initial'),
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_buyer', to='user_account.djolowinuser'),
        ),
        migrations.AddField(
            model_name='singleorder',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.singleordercard'),
        ),
        migrations.AddField(
            model_name='singlecard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.playercard'),
        ),
        migrations.AddField(
            model_name='ownedcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.playercard'),
        ),
        migrations.AddField(
            model_name='ownedcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.djolowinuser'),
        ),
        migrations.AddField(
            model_name='bundleorder',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.bundle'),
        ),
        migrations.AddField(
            model_name='bundleorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_buyer', to='user_account.djolowinuser'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='bundle_cards', to='base.playercard'),
        ),
    ]
