# Generated by Django 4.1 on 2022-08-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_alter_playercard_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateTimeField()),
                ('starting_bid', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.playercard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.djolowinuser')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('listed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.djolowinuser')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bids')),
            ],
        ),
    ]
