# Generated by Django 4.1 on 2022-09-18 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        ('trades', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.djolowinuser'),
        ),
        migrations.AddField(
            model_name='auctionwinner',
            name='winning_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='auctionedcard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.ownedcard'),
        ),
        migrations.AddField(
            model_name='auctionedcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.djolowinuser'),
        ),
    ]
