# Generated by Django 4.1 on 2022-08-28 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_bids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
