# Generated by Django 4.1 on 2022-08-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djolowinuser',
            name='email',
        ),
    ]
