# Generated by Django 4.1 on 2022-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_djolowinuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='djolowinuser',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=254),
            preserve_default=False,
        ),
    ]
