# Generated by Django 4.1 on 2022-08-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_djolowinuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djolowinuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='djolowinuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
