# Generated by Django 4.1 on 2022-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_djolowinuser_country_alter_djolowinuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='djolowinuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
